baseURL: /
title: Albatross theme - WebLizard
defaultContentLanguage: sv
theme: albatross

disableKinds:
  - taxonomy
  - term

params:
  copyrightOwner: 2022 WebLizard Albatross

  # Logo and icon to display
  logoPath: /img/albatross_logo.png
  iconPath: /img/albatross_icon.png

  style:
    # Base font size in px
    font-size: 18

    # Page content width factor
    page-content-width-factor: 42

    # Font size for different elements in rems
    font-size-h1: 1.8
    font-size-h2: 1.6
    font-size-h3: 1.4
    font-size-h4: 1.2

    # Font family
    font-family: sans

    # Colors
    light-background-color: '#fbf9fa' # light light blue
    light-foreground-color: '#000000' # black
    dark-background-color: '#2a2c31' # dark blue gray
    dark-foreground-color: '#ffffff' # white

    link-default-color: '#0000EE' # blue
    link-visited-color: '#551A8B' # purple

    # Menu item colors
    light-menu-background: '#e5e6ec' # light blue
    light-menu-foreground: '#000000' # black
    light-menu-item-hover-background: 'darken(#e5e6ec, 5%)'
    light-menu-item-hover-foreground: '#000000' # black

    dark-menu-background: '#27373f' # dark blue gray
    dark-menu-foreground: '#ffffff' # white
    dark-menu-item-hover-background: 'lighten(#27373f, 5%)'
    dark-menu-item-hover-foreground: '#ffffff' # white

    # Food menu flags
    food-menu-flags-vegan-background-color: '#006400' # darkgreen
    food-menu-flags-vegan-foreground-color: '#ffffff' # white
    food-menu-flags-vegetarian-background-color: '#006400' # darkgreen
    food-menu-flags-vegetarian-foreground-color: '#ffffff' # white
    food-menu-flags-gluten-free-background-color: '#f6d563' # Dark yellowish
    food-menu-flags-gluten-free-foreground-color: '#ffffff' # white
