baseURL: /
title: Albatross theme - WebLizard
defaultContentLanguage: sv
theme: albatross

disableKinds:
  - taxonomy
  - term

params:
  copyrightOwner: 2022 WebLizard Albatross
  showAttribution: true

  # Logo and icon to display
  logoPath: /img/albatross_logo.png
  iconPath: /img/albatross_icon.png

  style:
    # Base font size in px
    font-size: 18

    # Page content width factor
    page-content-width-factor: 42

    # Font size for different elements in rems
    font-size-h1: 1.8
    font-size-h2: 1.6
    font-size-h3: 1.4
    font-size-h4: 1.2

    # Font family
    font-family: sans

    # Light colors
    light-background-color: '#FBF9FA' # Seasalt
    light-border-color: '#000000' # Black
    light-foreground-color: 'contrast-color(#000000, #FBF9FA)' # Black, Seasalt
    light-link-default-color: 'contrast-color(#0000EE, #FBF9FA)' # Blue, Seasalt
    light-link-visited-color: 'contrast-color(#551A8B, #FBF9FA)' # Purple, Seasalt
    light-menu-background: '#E5E6EC' # Anti-flash white
    light-menu-foreground: 'contrast-color(#000000, #E5E6EC)' # Black, Anti-flash white
    light-menu-item-hover-background: 'darken(#E5E6EC, 5%)' # Anti-flash white
    light-menu-item-hover-foreground: 'contrast-color(#000000, #E5E6EC)' # Black, Anti-flash white
    light-food-menu-flags-gluten-free-background-color: '#F6D563' # Naples yellow
    light-food-menu-flags-gluten-free-foreground-color: 'contrast-color(#FFFFFF, #F6D563)' # White, Naples yellow
    light-food-menu-flags-vegan-background-color: '#006400' # Office Green
    light-food-menu-flags-vegan-foreground-color: 'contrast-color(#FFFFFF, #006400)' # White, Office Green
    light-food-menu-flags-vegetarian-background-color: '#006400' # Office Green
    light-food-menu-flags-vegetarian-foreground-color: 'contrast-color(#FFFFFF, #006400)' # White, Office Green


    # Dark colors
    dark-background-color: '#2A2C31' # Jet
    dark-border-color: '#000000' # Black
    dark-foreground-color: 'contrast-color(#000000, #2A2C31)' # Black, Jet
    dark-link-default-color: 'contrast-color(#0000EE, #2A2C31)' # Blue, Jet
    dark-link-visited-color: 'contrast-color(#551A8B, #2A2C31)' # Purple, Jet
    dark-menu-background: '#27373F' # Gunmetal
    dark-menu-foreground: 'contrast-color(#FFFFFF, #27373F)' # White, Gunmetal
    dark-menu-item-hover-background: 'lighten(#27373F, 5%)' # Gunmetal
    dark-menu-item-hover-foreground: 'contrast-color(#FFFFFF, lighten(#27373F, 5%))' # White, Gunmetal
    dark-food-menu-flags-gluten-free-background-color: '#F6D563' # Naples yellow
    dark-food-menu-flags-gluten-free-foreground-color: 'contrast-color(#FFFFFF, #F6D563)' # White, Naples yellow
    dark-food-menu-flags-vegan-background-color: '#006400' # Office Green
    dark-food-menu-flags-vegan-foreground-color: 'contrast-color(#FFFFFF, #006400)' # White, Office Green
    dark-food-menu-flags-vegetarian-background-color: '#006400' # Office Green
    dark-food-menu-flags-vegetarian-foreground-color: 'contrast-color(#FFFFFF, #006400)' # White, Office Green
